// Builds src/components/icon-paths.ts from the Phosphor icon set, keeping only
// the icons the app uses, so the bundle carries a few kilobytes, not 1,500 icons.
// Run with: node scripts/generate-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ICONS = [
  // Interface
  'plus', 'minus', 'x', 'check', 'check-circle', 'trash', 'arrow-left', 'arrow-right', 'caret-right', 'caret-down',
  'info', 'pencil-simple', 'share-network', 'arrow-counter-clockwise', 'github-logo', 'users-three',
  'receipt', 'scales', 'arrows-left-right', 'hand-coins', 'user-plus', 'warning-circle', 'sparkle', 'calendar-blank',
  'gear-six', 'magnifying-glass', 'caret-left', 'note-pencil', 'user-minus', 'door-open', 'globe-hemisphere-west',
  'arrows-down-up', 'arrows-clockwise', 'magic-wand', 'pencil-line', 'download-simple', 'lock-simple', 'upload-simple', 'link', 'shield-check', 'bug', 'arrow-clockwise', 'question', 'keyboard',
  'wallet', 'paper-plane-tilt', 'arrow-square-out', 'vibrate', 'repeat', 'archive', 'arrow-u-up-left', 'file-csv',
  // Expense categories
  'fork-knife', 'coffee', 'train', 'airplane-tilt', 'car', 'bed', 'house', 'lightning', 'shopping-bag',
  'ticket', 'gift', 'dots-three',
];

const root = join(process.cwd(), 'node_modules', '@phosphor-icons', 'core');
const camel = (name) => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const entries = ICONS.map((name) => {
  const svg = readFileSync(join(root, 'assets', 'regular', `${name}.svg`), 'utf8');
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((match) => match[1]);
  if (paths.length === 0) throw new Error(`No paths in ${name}`);
  return `  ${camel(name)}: ${JSON.stringify(paths)},`;
});

writeFileSync(
  join(process.cwd(), 'src', 'components', 'icon-paths.ts'),
  `// Generated by scripts/generate-icons.mjs. Do not edit by hand.
// Icons from Phosphor (https://phosphoricons.com), MIT License, Copyright (c) 2023 Phosphor Icons.
// Regular weight, drawn on a 256 x 256 grid.
export const iconPaths = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof iconPaths;
`
);
console.log(`Wrote ${ICONS.length} icons`);
